[project]
name = "lab-tracker"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "pydantic-settings>=2.11.0",
    "pymupdf>=1.26.5",
    "yandex-cloud-ml-sdk>=0.16.0",
]
